/** \file
 *  This C source file was generated by $ANTLR version 3.5
 *
 *     -  From the grammar source file : artilib\\grammars\\Feat.g
 *     -                            On : 2013-09-29 15:14:48
 *     -                for the parser : FeatParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "FeatParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pFeatParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pFeatParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pFeatParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pFeatParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   FeatParserTokenNames[13+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INTEGER",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'!'",
        (pANTLR3_UINT8) "'&'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'@'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'|'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 FeatParser_formula_return
	formula    (pFeatParser ctx);
static 
 FeatParser_term_return
	term    (pFeatParser ctx);
static 
 FeatParser_orExpr_return
	orExpr    (pFeatParser ctx);
static 
 FeatParser_andExpr_return
	andExpr    (pFeatParser ctx);
static 
 FeatParser_ground_return
	ground    (pFeatParser ctx);
static 
 FeatParser_state_set_return
	state_set    (pFeatParser ctx);
static 
 FeatParser_square_set_return
	square_set    (pFeatParser ctx);
static 
 FeatParser_square_return
	square    (pFeatParser ctx);
static void	FeatParserFree(pFeatParser ctx);
static void     FeatParserReset (pFeatParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "artilib\\grammars\\Feat.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new FeatParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pFeatParser
FeatParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return FeatParserNewSSD(instream, NULL);
}

/** \brief Create a new FeatParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pFeatParser
FeatParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pFeatParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pFeatParser) ANTLR3_CALLOC(1, sizeof(FeatParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in FeatParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our FeatParser interface
     */
    ctx->formula	= formula;
    ctx->term	= term;
    ctx->orExpr	= orExpr;
    ctx->andExpr	= andExpr;
    ctx->ground	= ground;
    ctx->state_set	= state_set;
    ctx->square_set	= square_set;
    ctx->square	= square;
    ctx->free			= FeatParserFree;
    ctx->reset			= FeatParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = FeatParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
FeatParserReset (pFeatParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 FeatParserFree(pFeatParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return FeatParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_orExpr_in_formula42  */
static	ANTLR3_BITWORD FOLLOW_orExpr_in_formula42_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_orExpr_in_formula42	= { FOLLOW_orExpr_in_formula42_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ground_in_term56  */
static	ANTLR3_BITWORD FOLLOW_ground_in_term56_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ground_in_term56	= { FOLLOW_ground_in_term56_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_term61  */
static	ANTLR3_BITWORD FOLLOW_10_in_term61_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004500) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_term61	= { FOLLOW_10_in_term61_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_orExpr_in_term63  */
static	ANTLR3_BITWORD FOLLOW_orExpr_in_term63_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_orExpr_in_term63	= { FOLLOW_orExpr_in_term63_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_term65  */
static	ANTLR3_BITWORD FOLLOW_11_in_term65_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_term65	= { FOLLOW_11_in_term65_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_term70  */
static	ANTLR3_BITWORD FOLLOW_8_in_term70_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004500) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_term70	= { FOLLOW_8_in_term70_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_term72  */
static	ANTLR3_BITWORD FOLLOW_term_in_term72_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_term72	= { FOLLOW_term_in_term72_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_andExpr_in_orExpr81  */
static	ANTLR3_BITWORD FOLLOW_andExpr_in_orExpr81_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008002) };
static  ANTLR3_BITSET_LIST FOLLOW_andExpr_in_orExpr81	= { FOLLOW_andExpr_in_orExpr81_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_orExpr84  */
static	ANTLR3_BITWORD FOLLOW_15_in_orExpr84_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004500) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_orExpr84	= { FOLLOW_15_in_orExpr84_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_andExpr_in_orExpr86  */
static	ANTLR3_BITWORD FOLLOW_andExpr_in_orExpr86_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008002) };
static  ANTLR3_BITSET_LIST FOLLOW_andExpr_in_orExpr86	= { FOLLOW_andExpr_in_orExpr86_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_andExpr97  */
static	ANTLR3_BITWORD FOLLOW_term_in_andExpr97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000202) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_andExpr97	= { FOLLOW_term_in_andExpr97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_andExpr100  */
static	ANTLR3_BITWORD FOLLOW_9_in_andExpr100_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004500) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_andExpr100	= { FOLLOW_9_in_andExpr100_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_andExpr102  */
static	ANTLR3_BITWORD FOLLOW_term_in_andExpr102_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000202) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_andExpr102	= { FOLLOW_term_in_andExpr102_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_state_set_in_ground116  */
static	ANTLR3_BITWORD FOLLOW_state_set_in_ground116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_state_set_in_ground116	= { FOLLOW_state_set_in_ground116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_ground118  */
static	ANTLR3_BITWORD FOLLOW_13_in_ground118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_ground118	= { FOLLOW_13_in_ground118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_square_set_in_ground120  */
static	ANTLR3_BITWORD FOLLOW_square_set_in_ground120_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_square_set_in_ground120	= { FOLLOW_square_set_in_ground120_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_state_set131  */
static	ANTLR3_BITWORD FOLLOW_14_in_state_set131_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_state_set131	= { FOLLOW_14_in_state_set131_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_state_set133  */
static	ANTLR3_BITWORD FOLLOW_ID_in_state_set133_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010020) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_state_set133	= { FOLLOW_ID_in_state_set133_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_state_set136  */
static	ANTLR3_BITWORD FOLLOW_ID_in_state_set136_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010020) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_state_set136	= { FOLLOW_ID_in_state_set136_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_state_set140  */
static	ANTLR3_BITWORD FOLLOW_16_in_state_set140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_state_set140	= { FOLLOW_16_in_state_set140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_square_set151  */
static	ANTLR3_BITWORD FOLLOW_14_in_square_set151_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_square_set151	= { FOLLOW_14_in_square_set151_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_square_in_square_set153  */
static	ANTLR3_BITWORD FOLLOW_square_in_square_set153_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010040) };
static  ANTLR3_BITSET_LIST FOLLOW_square_in_square_set153	= { FOLLOW_square_in_square_set153_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_square_in_square_set156  */
static	ANTLR3_BITWORD FOLLOW_square_in_square_set156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010040) };
static  ANTLR3_BITSET_LIST FOLLOW_square_in_square_set156	= { FOLLOW_square_in_square_set156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_square_set160  */
static	ANTLR3_BITWORD FOLLOW_16_in_square_set160_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_square_set160	= { FOLLOW_16_in_square_set160_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INTEGER_in_square172  */
static	ANTLR3_BITWORD FOLLOW_INTEGER_in_square172_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_INTEGER_in_square172	= { FOLLOW_INTEGER_in_square172_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_square174  */
static	ANTLR3_BITWORD FOLLOW_12_in_square174_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_square174	= { FOLLOW_12_in_square174_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INTEGER_in_square176  */
static	ANTLR3_BITWORD FOLLOW_INTEGER_in_square176_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INTEGER_in_square176	= { FOLLOW_INTEGER_in_square176_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start formula
 * artilib\\grammars\\Feat.g:9:1: formula : orExpr ;
 */
static FeatParser_formula_return
formula(pFeatParser ctx)
{
    FeatParser_formula_return retval;


    pANTLR3_BASE_TREE root_0;

    FeatParser_orExpr_return orExpr1;
    #undef	RETURN_TYPE_orExpr1
    #define	RETURN_TYPE_orExpr1 FeatParser_orExpr_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    orExpr1.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:10:2: ( orExpr )
        // artilib\\grammars\\Feat.g:10:4: orExpr
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_orExpr_in_formula42);
            orExpr1=orExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleformulaEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, orExpr1.tree);

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleformulaEx; /* Prevent compiler warnings */
    ruleformulaEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end formula */

/**
 * $ANTLR start term
 * artilib\\grammars\\Feat.g:13:1: term : ( ground | '(' orExpr ')' | '!' term );
 */
static FeatParser_term_return
term(pFeatParser ctx)
{
    FeatParser_term_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal3;
    pANTLR3_COMMON_TOKEN    char_literal5;
    pANTLR3_COMMON_TOKEN    char_literal6;
    FeatParser_ground_return ground2;
    #undef	RETURN_TYPE_ground2
    #define	RETURN_TYPE_ground2 FeatParser_ground_return

    FeatParser_orExpr_return orExpr4;
    #undef	RETURN_TYPE_orExpr4
    #define	RETURN_TYPE_orExpr4 FeatParser_orExpr_return

    FeatParser_term_return term7;
    #undef	RETURN_TYPE_term7
    #define	RETURN_TYPE_term7 FeatParser_term_return

    pANTLR3_BASE_TREE char_literal3_tree;
    pANTLR3_BASE_TREE char_literal5_tree;
    pANTLR3_BASE_TREE char_literal6_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal3       = NULL;
    char_literal5       = NULL;
    char_literal6       = NULL;
    ground2.tree = NULL;

    orExpr4.tree = NULL;

    term7.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal3_tree   = NULL;
    char_literal5_tree   = NULL;
    char_literal6_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  artilib\\grammars\\Feat.g:14:2: ( ground | '(' orExpr ')' | '!' term )

            ANTLR3_UINT32 alt1;

            alt1=3;

            switch ( LA(1) )
            {
            case 14:
            	{
            		alt1=1;
            	}
                break;
            case 10:
            	{
            		alt1=2;
            	}
                break;
            case 8:
            	{
            		alt1=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto ruletermEx;

            }

            switch (alt1)
            {
        	case 1:
        	    // artilib\\grammars\\Feat.g:14:4: ground
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_ground_in_term56);
        	        ground2=ground(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, ground2.tree);

        	    }
        	    break;
        	case 2:
        	    // artilib\\grammars\\Feat.g:15:4: '(' orExpr ')'
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal3 = (pANTLR3_COMMON_TOKEN) MATCHT(10, &FOLLOW_10_in_term61);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }

        	        char_literal3_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal3));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal3_tree);


        	        FOLLOWPUSH(FOLLOW_orExpr_in_term63);
        	        orExpr4=orExpr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, orExpr4.tree);

        	        char_literal5 = (pANTLR3_COMMON_TOKEN) MATCHT(11, &FOLLOW_11_in_term65);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }

        	        char_literal5_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal5));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal5_tree);


        	    }
        	    break;
        	case 3:
        	    // artilib\\grammars\\Feat.g:16:4: '!' term
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal6 = (pANTLR3_COMMON_TOKEN) MATCHT(8, &FOLLOW_8_in_term70);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }

        	        char_literal6_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal6));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal6_tree);


        	        FOLLOWPUSH(FOLLOW_term_in_term72);
        	        term7=term(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, term7.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruletermEx; /* Prevent compiler warnings */
    ruletermEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end term */

/**
 * $ANTLR start orExpr
 * artilib\\grammars\\Feat.g:18:1: orExpr : andExpr ( '|' andExpr )* ;
 */
static FeatParser_orExpr_return
orExpr(pFeatParser ctx)
{
    FeatParser_orExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal9;
    FeatParser_andExpr_return andExpr8;
    #undef	RETURN_TYPE_andExpr8
    #define	RETURN_TYPE_andExpr8 FeatParser_andExpr_return

    FeatParser_andExpr_return andExpr10;
    #undef	RETURN_TYPE_andExpr10
    #define	RETURN_TYPE_andExpr10 FeatParser_andExpr_return

    pANTLR3_BASE_TREE char_literal9_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal9       = NULL;
    andExpr8.tree = NULL;

    andExpr10.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal9_tree   = NULL;


    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:19:2: ( andExpr ( '|' andExpr )* )
        // artilib\\grammars\\Feat.g:19:4: andExpr ( '|' andExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_andExpr_in_orExpr81);
            andExpr8=andExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleorExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, andExpr8.tree);

            // artilib\\grammars\\Feat.g:19:12: ( '|' andExpr )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case 15:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // artilib\\grammars\\Feat.g:19:13: '|' andExpr
            	    {
            	        char_literal9 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_orExpr84);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleorExprEx;
            	        }

            	        char_literal9_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal9));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal9_tree);


            	        FOLLOWPUSH(FOLLOW_andExpr_in_orExpr86);
            	        andExpr10=andExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleorExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, andExpr10.tree);

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleorExprEx; /* Prevent compiler warnings */
    ruleorExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end orExpr */

/**
 * $ANTLR start andExpr
 * artilib\\grammars\\Feat.g:21:1: andExpr : term ( '&' term )* ;
 */
static FeatParser_andExpr_return
andExpr(pFeatParser ctx)
{
    FeatParser_andExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal12;
    FeatParser_term_return term11;
    #undef	RETURN_TYPE_term11
    #define	RETURN_TYPE_term11 FeatParser_term_return

    FeatParser_term_return term13;
    #undef	RETURN_TYPE_term13
    #define	RETURN_TYPE_term13 FeatParser_term_return

    pANTLR3_BASE_TREE char_literal12_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal12       = NULL;
    term11.tree = NULL;

    term13.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal12_tree   = NULL;


    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:22:2: ( term ( '&' term )* )
        // artilib\\grammars\\Feat.g:22:4: term ( '&' term )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_term_in_andExpr97);
            term11=term(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleandExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, term11.tree);

            // artilib\\grammars\\Feat.g:22:9: ( '&' term )*

            for (;;)
            {
                int alt3=2;
                switch ( LA(1) )
                {
                case 9:
                	{
                		alt3=1;
                	}
                    break;

                }

                switch (alt3)
                {
            	case 1:
            	    // artilib\\grammars\\Feat.g:22:10: '&' term
            	    {
            	        char_literal12 = (pANTLR3_COMMON_TOKEN) MATCHT(9, &FOLLOW_9_in_andExpr100);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleandExprEx;
            	        }

            	        char_literal12_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal12));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal12_tree);


            	        FOLLOWPUSH(FOLLOW_term_in_andExpr102);
            	        term13=term(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleandExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, term13.tree);

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleandExprEx; /* Prevent compiler warnings */
    ruleandExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end andExpr */

/**
 * $ANTLR start ground
 * artilib\\grammars\\Feat.g:25:1: ground : state_set '@' square_set ;
 */
static FeatParser_ground_return
ground(pFeatParser ctx)
{
    FeatParser_ground_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal15;
    FeatParser_state_set_return state_set14;
    #undef	RETURN_TYPE_state_set14
    #define	RETURN_TYPE_state_set14 FeatParser_state_set_return

    FeatParser_square_set_return square_set16;
    #undef	RETURN_TYPE_square_set16
    #define	RETURN_TYPE_square_set16 FeatParser_square_set_return

    pANTLR3_BASE_TREE char_literal15_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal15       = NULL;
    state_set14.tree = NULL;

    square_set16.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal15_tree   = NULL;


    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:26:2: ( state_set '@' square_set )
        // artilib\\grammars\\Feat.g:26:4: state_set '@' square_set
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_state_set_in_ground116);
            state_set14=state_set(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulegroundEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, state_set14.tree);

            char_literal15 = (pANTLR3_COMMON_TOKEN) MATCHT(13, &FOLLOW_13_in_ground118);
            if  (HASEXCEPTION())
            {
                goto rulegroundEx;
            }

            char_literal15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal15));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal15_tree);


            FOLLOWPUSH(FOLLOW_square_set_in_ground120);
            square_set16=square_set(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulegroundEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, square_set16.tree);

        }

    }

    // This is where rules clean up and exit
    //
    goto rulegroundEx; /* Prevent compiler warnings */
    rulegroundEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end ground */

/**
 * $ANTLR start state_set
 * artilib\\grammars\\Feat.g:29:1: state_set : '{' ID ( ID )* '}' ;
 */
static FeatParser_state_set_return
state_set(pFeatParser ctx)
{
    FeatParser_state_set_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal17;
    pANTLR3_COMMON_TOKEN    ID18;
    pANTLR3_COMMON_TOKEN    ID19;
    pANTLR3_COMMON_TOKEN    char_literal20;

    pANTLR3_BASE_TREE char_literal17_tree;
    pANTLR3_BASE_TREE ID18_tree;
    pANTLR3_BASE_TREE ID19_tree;
    pANTLR3_BASE_TREE char_literal20_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal17       = NULL;
    ID18       = NULL;
    ID19       = NULL;
    char_literal20       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal17_tree   = NULL;
    ID18_tree   = NULL;
    ID19_tree   = NULL;
    char_literal20_tree   = NULL;


    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:30:2: ( '{' ID ( ID )* '}' )
        // artilib\\grammars\\Feat.g:30:4: '{' ID ( ID )* '}'
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            char_literal17 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_state_set131);
            if  (HASEXCEPTION())
            {
                goto rulestate_setEx;
            }

            char_literal17_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal17));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal17_tree);


            ID18 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_state_set133);
            if  (HASEXCEPTION())
            {
                goto rulestate_setEx;
            }

            ID18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID18));
            ADAPTOR->addChild(ADAPTOR, root_0, ID18_tree);


            // artilib\\grammars\\Feat.g:30:11: ( ID )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case ID:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // artilib\\grammars\\Feat.g:30:12: ID
            	    {
            	        ID19 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_state_set136);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestate_setEx;
            	        }

            	        ID19_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID19));
            	        ADAPTOR->addChild(ADAPTOR, root_0, ID19_tree);


            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


            char_literal20 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_state_set140);
            if  (HASEXCEPTION())
            {
                goto rulestate_setEx;
            }

            char_literal20_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal20));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal20_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestate_setEx; /* Prevent compiler warnings */
    rulestate_setEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end state_set */

/**
 * $ANTLR start square_set
 * artilib\\grammars\\Feat.g:33:1: square_set : '{' square ( square )* '}' ;
 */
static FeatParser_square_set_return
square_set(pFeatParser ctx)
{
    FeatParser_square_set_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal21;
    pANTLR3_COMMON_TOKEN    char_literal24;
    FeatParser_square_return square22;
    #undef	RETURN_TYPE_square22
    #define	RETURN_TYPE_square22 FeatParser_square_return

    FeatParser_square_return square23;
    #undef	RETURN_TYPE_square23
    #define	RETURN_TYPE_square23 FeatParser_square_return

    pANTLR3_BASE_TREE char_literal21_tree;
    pANTLR3_BASE_TREE char_literal24_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal21       = NULL;
    char_literal24       = NULL;
    square22.tree = NULL;

    square23.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal21_tree   = NULL;
    char_literal24_tree   = NULL;


    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:34:2: ( '{' square ( square )* '}' )
        // artilib\\grammars\\Feat.g:34:4: '{' square ( square )* '}'
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            char_literal21 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_square_set151);
            if  (HASEXCEPTION())
            {
                goto rulesquare_setEx;
            }

            char_literal21_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal21));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal21_tree);


            FOLLOWPUSH(FOLLOW_square_in_square_set153);
            square22=square(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesquare_setEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, square22.tree);

            // artilib\\grammars\\Feat.g:34:15: ( square )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case INTEGER:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5)
                {
            	case 1:
            	    // artilib\\grammars\\Feat.g:34:16: square
            	    {
            	        FOLLOWPUSH(FOLLOW_square_in_square_set156);
            	        square23=square(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesquare_setEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, square23.tree);

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


            char_literal24 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_square_set160);
            if  (HASEXCEPTION())
            {
                goto rulesquare_setEx;
            }

            char_literal24_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal24));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal24_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesquare_setEx; /* Prevent compiler warnings */
    rulesquare_setEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end square_set */

/**
 * $ANTLR start square
 * artilib\\grammars\\Feat.g:37:1: square : INTEGER '.' INTEGER ;
 */
static FeatParser_square_return
square(pFeatParser ctx)
{
    FeatParser_square_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INTEGER25;
    pANTLR3_COMMON_TOKEN    char_literal26;
    pANTLR3_COMMON_TOKEN    INTEGER27;

    pANTLR3_BASE_TREE INTEGER25_tree;
    pANTLR3_BASE_TREE char_literal26_tree;
    pANTLR3_BASE_TREE INTEGER27_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INTEGER25       = NULL;
    char_literal26       = NULL;
    INTEGER27       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INTEGER25_tree   = NULL;
    char_literal26_tree   = NULL;
    INTEGER27_tree   = NULL;


    retval.tree  = NULL;

    {
        // artilib\\grammars\\Feat.g:38:2: ( INTEGER '.' INTEGER )
        // artilib\\grammars\\Feat.g:38:5: INTEGER '.' INTEGER
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            INTEGER25 = (pANTLR3_COMMON_TOKEN) MATCHT(INTEGER, &FOLLOW_INTEGER_in_square172);
            if  (HASEXCEPTION())
            {
                goto rulesquareEx;
            }

            INTEGER25_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INTEGER25));
            ADAPTOR->addChild(ADAPTOR, root_0, INTEGER25_tree);


            char_literal26 = (pANTLR3_COMMON_TOKEN) MATCHT(12, &FOLLOW_12_in_square174);
            if  (HASEXCEPTION())
            {
                goto rulesquareEx;
            }

            char_literal26_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal26));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal26_tree);


            INTEGER27 = (pANTLR3_COMMON_TOKEN) MATCHT(INTEGER, &FOLLOW_INTEGER_in_square176);
            if  (HASEXCEPTION())
            {
                goto rulesquareEx;
            }

            INTEGER27_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INTEGER27));
            ADAPTOR->addChild(ADAPTOR, root_0, INTEGER27_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesquareEx; /* Prevent compiler warnings */
    rulesquareEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end square */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
